services:  
  mysql:
    container_name: mysql-srv01
    image: mysql:8.0-debian
    restart: always
    ports:
      - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: ${TZ}
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - mysql-srv01:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PMA_APP_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: ${ROOT_PASSWORD}
volumes:
  mysql-srv01:
